# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\02_workspace\python\self\untitled\qss\qsswindow.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_QSSWindow(object):
    def setupUi(self, QSSWindow):
        QSSWindow.setObjectName("QSSWindow")
        QSSWindow.resize(625, 407)
        self.centralwidget = QtWidgets.QWidget(QSSWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_3.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_3.addWidget(self.radioButton_2)
        self.checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_3.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout_3.addWidget(self.checkBox_2)
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_3.addWidget(self.comboBox)
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_2.setObjectName("comboBox_2")
        self.horizontalLayout_3.addWidget(self.comboBox_2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.messageBtn = QtWidgets.QPushButton(self.groupBox)
        self.messageBtn.setStyleSheet("")
        self.messageBtn.setObjectName("messageBtn")
        self.horizontalLayout.addWidget(self.messageBtn)
        self.tipBtn = QtWidgets.QPushButton(self.groupBox)
        self.tipBtn.setStyleSheet("")
        self.tipBtn.setObjectName("tipBtn")
        self.horizontalLayout.addWidget(self.tipBtn)
        self.errorBtn = QtWidgets.QPushButton(self.groupBox)
        self.errorBtn.setStyleSheet("")
        self.errorBtn.setObjectName("errorBtn")
        self.horizontalLayout.addWidget(self.errorBtn)
        self.standInBtn = QtWidgets.QPushButton(self.groupBox)
        self.standInBtn.setStyleSheet("")
        self.standInBtn.setObjectName("standInBtn")
        self.horizontalLayout.addWidget(self.standInBtn)
        self.passBtn = QtWidgets.QPushButton(self.groupBox)
        self.passBtn.setStyleSheet("")
        self.passBtn.setObjectName("passBtn")
        self.horizontalLayout.addWidget(self.passBtn)
        self.inputBtn = QtWidgets.QPushButton(self.groupBox)
        self.inputBtn.setStyleSheet("")
        self.inputBtn.setObjectName("inputBtn")
        self.horizontalLayout.addWidget(self.inputBtn)
        self.newWindowBtn = QtWidgets.QPushButton(self.groupBox)
        self.newWindowBtn.setStyleSheet("")
        self.newWindowBtn.setObjectName("newWindowBtn")
        self.horizontalLayout.addWidget(self.newWindowBtn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.spinBox = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox.setMouseTracking(False)
        self.spinBox.setStyleSheet("")
        self.spinBox.setAccelerated(False)
        self.spinBox.setProperty("showGroupSeparator", False)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_4.addWidget(self.spinBox)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.horizontalLayout_4.addWidget(self.doubleSpinBox)
        self.timeEdit = QtWidgets.QTimeEdit(self.groupBox)
        self.timeEdit.setObjectName("timeEdit")
        self.horizontalLayout_4.addWidget(self.timeEdit)
        self.dateEdit = QtWidgets.QDateEdit(self.groupBox)
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout_4.addWidget(self.dateEdit)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.groupBox)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.horizontalLayout_4.addWidget(self.dateTimeEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalSlider = QtWidgets.QSlider(self.groupBox)
        self.horizontalSlider.setMaximum(100)
        self.horizontalSlider.setProperty("value", 50)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setTickInterval(0)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalLayout_5.addWidget(self.horizontalSlider)
        self.progressBar = QtWidgets.QProgressBar(self.groupBox)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_5.addWidget(self.progressBar)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.textEdit = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox.raise_()
        self.groupBox.raise_()
        self.tabWidget.addTab(self.tab, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.tabWidget.addTab(self.tab_6, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        QSSWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(QSSWindow)
        self.statusbar.setObjectName("statusbar")
        QSSWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(QSSWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 625, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        QSSWindow.setMenuBar(self.menubar)
        self.actionFile = QtWidgets.QAction(QSSWindow)
        self.actionFile.setObjectName("actionFile")
        self.actionNew = QtWidgets.QAction(QSSWindow)
        self.actionNew.setObjectName("actionNew")
        self.menu.addAction(self.actionFile)
        self.menu.addSeparator()
        self.menu.addAction(self.actionNew)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(QSSWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(QSSWindow)

    def retranslateUi(self, QSSWindow):
        _translate = QtCore.QCoreApplication.translate
        QSSWindow.setWindowTitle(_translate("QSSWindow", "MainWindow"))
        self.tabWidget.setToolTip(_translate("QSSWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.tabWidget.setWhatsThis(_translate("QSSWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.groupBox.setTitle(_translate("QSSWindow", "GroupBox"))
        self.label.setText(_translate("QSSWindow", "TextLabel"))
        self.radioButton.setText(_translate("QSSWindow", "RadioButton"))
        self.radioButton_2.setText(_translate("QSSWindow", "RadioButton"))
        self.checkBox.setText(_translate("QSSWindow", "CheckBox"))
        self.checkBox_2.setText(_translate("QSSWindow", "CheckBox"))
        self.messageBtn.setText(_translate("QSSWindow", "信息框"))
        self.tipBtn.setText(_translate("QSSWindow", "提示框"))
        self.errorBtn.setText(_translate("QSSWindow", "错误框"))
        self.standInBtn.setText(_translate("QSSWindow", "标准输入框"))
        self.passBtn.setText(_translate("QSSWindow", "密码输入框"))
        self.inputBtn.setText(_translate("QSSWindow", "下拉输入框"))
        self.newWindowBtn.setText(_translate("QSSWindow", "新窗体"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("QSSWindow", "常用组件"))
        self.tab_7.setWhatsThis(_translate("QSSWindow", "<html><head/><body><p>12</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("QSSWindow", "表格数据"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("QSSWindow", "导航界面"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("QSSWindow", "树状列表"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("QSSWindow", "日历效果"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("QSSWindow", "tab选项卡"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("QSSWindow", "设备面板"))
        self.menu.setTitle(_translate("QSSWindow", "文件"))
        self.menu_2.setTitle(_translate("QSSWindow", "编辑"))
        self.actionFile.setText(_translate("QSSWindow", "新建文件"))
        self.actionNew.setText(_translate("QSSWindow", "打开文件"))

